// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/FestivalProtocol.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Ro.Mpp2025.Protobuffprotocol {

  /// <summary>Holder for reflection information generated from proto/FestivalProtocol.proto</summary>
  public static partial class FestivalProtocolReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/FestivalProtocol.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FestivalProtocolReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chxwcm90by9GZXN0aXZhbFByb3RvY29sLnByb3RvEhxyby5tcHAyMDI1LnBy",
            "b3RvYnVmZnByb3RvY29sInwKCVNwZWN0YWNvbBIKCgJpZBgBIAEoBRIOCgZh",
            "cnRpc3QYAiABKAkSDAoEZGF0YRgDIAEoCRIPCgdsb2NhdGllGAQgASgJEhsK",
            "E25yTG9jdXJpRGlzcG9uaWJpbGUYBSABKAUSFwoPbnJMb2N1cmlWYW5kdXRl",
            "GAYgASgFImoKBUJpbGV0EjoKCXNwZWN0YWNvbBgBIAEoCzInLnJvLm1wcDIw",
            "MjUucHJvdG9idWZmcHJvdG9jb2wuU3BlY3RhY29sEhYKDmN1bXBhcmF0b3JO",
            "YW1lGAIgASgJEg0KBXNlYXRzGAMgASgFIi0KB0FuZ2FqYXQSEAoIdXNlcm5h",
            "bWUYASABKAkSEAoIcGFzc3dvcmQYAiABKAkipwIKB1JlcXVlc3QSOAoEdHlw",
            "ZRgBIAEoDjIqLnJvLm1wcDIwMjUucHJvdG9idWZmcHJvdG9jb2wuUmVxdWVz",
            "dC5UeXBlEjgKB2FuZ2FqYXQYAiABKAsyJS5yby5tcHAyMDI1LnByb3RvYnVm",
            "ZnByb3RvY29sLkFuZ2FqYXRIABINCgNkYXkYAyABKAlIABI0CgViaWxldBgE",
            "IAEoCzIjLnJvLm1wcDIwMjUucHJvdG9idWZmcHJvdG9jb2wuQmlsZXRIACJY",
            "CgRUeXBlEgoKBlVua293bhAAEgkKBUxvZ2luEAESEQoNR2V0U3BlY3RhY29s",
            "ZRACEhQKEEZpbHRlclNwZWN0YWNvbGUQAxIQCgxSZXNlcnZlQmlsZXQQBEIJ",
            "CgdwYXlsb2FkIskDCghSZXNwb25zZRI5CgR0eXBlGAEgASgOMisucm8ubXBw",
            "MjAyNS5wcm90b2J1ZmZwcm90b2NvbC5SZXNwb25zZS5UeXBlEg0KBWVycm9y",
            "GAIgASgJEjsKCnNwZWN0YWNvbGUYAyADKAsyJy5yby5tcHAyMDI1LnByb3Rv",
            "YnVmZnByb3RvY29sLlNwZWN0YWNvbBI5CghmaWx0ZXJlZBgEIAMoCzInLnJv",
            "Lm1wcDIwMjUucHJvdG9idWZmcHJvdG9jb2wuU3BlY3RhY29sEjYKB2FuZ2Fq",
            "YXQYBSABKAsyJS5yby5tcHAyMDI1LnByb3RvYnVmZnByb3RvY29sLkFuZ2Fq",
            "YXQSOgoJc3BlY3RhY29sGAYgASgLMicucm8ubXBwMjAyNS5wcm90b2J1ZmZw",
            "cm90b2NvbC5TcGVjdGFjb2wihgEKBFR5cGUSCwoHVW5rbm93bhAAEgYKAk9r",
            "EAESCQoFRXJyb3IQAhIRCg1HZXRTcGVjdGFjb2xlEAMSFAoQRmlsdGVyU3Bl",
            "Y3RhY29sZRAEEhAKDFJlc2VydmVCaWxldBAFEg4KClNwZWN0YWNvbGUQBhIT",
            "Cg91cGRhdGVTcGVjdGFjb2wQB0IgCglwcm90b2J1ZmZCEUZlc3RpdmFsUHJv",
            "dG9idWZzUABiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Ro.Mpp2025.Protobuffprotocol.Spectacol), global::Ro.Mpp2025.Protobuffprotocol.Spectacol.Parser, new[]{ "Id", "Artist", "Data", "Locatie", "NrLocuriDisponibile", "NrLocuriVandute" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ro.Mpp2025.Protobuffprotocol.Bilet), global::Ro.Mpp2025.Protobuffprotocol.Bilet.Parser, new[]{ "Spectacol", "CumparatorName", "Seats" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ro.Mpp2025.Protobuffprotocol.Angajat), global::Ro.Mpp2025.Protobuffprotocol.Angajat.Parser, new[]{ "Username", "Password" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ro.Mpp2025.Protobuffprotocol.Request), global::Ro.Mpp2025.Protobuffprotocol.Request.Parser, new[]{ "Type", "Angajat", "Day", "Bilet" }, new[]{ "Payload" }, new[]{ typeof(global::Ro.Mpp2025.Protobuffprotocol.Request.Types.Type) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Ro.Mpp2025.Protobuffprotocol.Response), global::Ro.Mpp2025.Protobuffprotocol.Response.Parser, new[]{ "Type", "Error", "Spectacole", "Filtered", "Angajat", "Spectacol" }, null, new[]{ typeof(global::Ro.Mpp2025.Protobuffprotocol.Response.Types.Type) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Spectacol : pb::IMessage<Spectacol>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Spectacol> _parser = new pb::MessageParser<Spectacol>(() => new Spectacol());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Spectacol> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ro.Mpp2025.Protobuffprotocol.FestivalProtocolReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Spectacol() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Spectacol(Spectacol other) : this() {
      id_ = other.id_;
      artist_ = other.artist_;
      data_ = other.data_;
      locatie_ = other.locatie_;
      nrLocuriDisponibile_ = other.nrLocuriDisponibile_;
      nrLocuriVandute_ = other.nrLocuriVandute_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Spectacol Clone() {
      return new Spectacol(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "artist" field.</summary>
    public const int ArtistFieldNumber = 2;
    private string artist_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Artist {
      get { return artist_; }
      set {
        artist_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 3;
    private string data_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "locatie" field.</summary>
    public const int LocatieFieldNumber = 4;
    private string locatie_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Locatie {
      get { return locatie_; }
      set {
        locatie_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nrLocuriDisponibile" field.</summary>
    public const int NrLocuriDisponibileFieldNumber = 5;
    private int nrLocuriDisponibile_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NrLocuriDisponibile {
      get { return nrLocuriDisponibile_; }
      set {
        nrLocuriDisponibile_ = value;
      }
    }

    /// <summary>Field number for the "nrLocuriVandute" field.</summary>
    public const int NrLocuriVanduteFieldNumber = 6;
    private int nrLocuriVandute_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NrLocuriVandute {
      get { return nrLocuriVandute_; }
      set {
        nrLocuriVandute_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Spectacol);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Spectacol other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Artist != other.Artist) return false;
      if (Data != other.Data) return false;
      if (Locatie != other.Locatie) return false;
      if (NrLocuriDisponibile != other.NrLocuriDisponibile) return false;
      if (NrLocuriVandute != other.NrLocuriVandute) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Artist.Length != 0) hash ^= Artist.GetHashCode();
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      if (Locatie.Length != 0) hash ^= Locatie.GetHashCode();
      if (NrLocuriDisponibile != 0) hash ^= NrLocuriDisponibile.GetHashCode();
      if (NrLocuriVandute != 0) hash ^= NrLocuriVandute.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Artist.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Artist);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Data);
      }
      if (Locatie.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Locatie);
      }
      if (NrLocuriDisponibile != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(NrLocuriDisponibile);
      }
      if (NrLocuriVandute != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(NrLocuriVandute);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Artist.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Artist);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Data);
      }
      if (Locatie.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Locatie);
      }
      if (NrLocuriDisponibile != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(NrLocuriDisponibile);
      }
      if (NrLocuriVandute != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(NrLocuriVandute);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Artist.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Artist);
      }
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Data);
      }
      if (Locatie.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Locatie);
      }
      if (NrLocuriDisponibile != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NrLocuriDisponibile);
      }
      if (NrLocuriVandute != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NrLocuriVandute);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Spectacol other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Artist.Length != 0) {
        Artist = other.Artist;
      }
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
      if (other.Locatie.Length != 0) {
        Locatie = other.Locatie;
      }
      if (other.NrLocuriDisponibile != 0) {
        NrLocuriDisponibile = other.NrLocuriDisponibile;
      }
      if (other.NrLocuriVandute != 0) {
        NrLocuriVandute = other.NrLocuriVandute;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Artist = input.ReadString();
            break;
          }
          case 26: {
            Data = input.ReadString();
            break;
          }
          case 34: {
            Locatie = input.ReadString();
            break;
          }
          case 40: {
            NrLocuriDisponibile = input.ReadInt32();
            break;
          }
          case 48: {
            NrLocuriVandute = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Artist = input.ReadString();
            break;
          }
          case 26: {
            Data = input.ReadString();
            break;
          }
          case 34: {
            Locatie = input.ReadString();
            break;
          }
          case 40: {
            NrLocuriDisponibile = input.ReadInt32();
            break;
          }
          case 48: {
            NrLocuriVandute = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Bilet : pb::IMessage<Bilet>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Bilet> _parser = new pb::MessageParser<Bilet>(() => new Bilet());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Bilet> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ro.Mpp2025.Protobuffprotocol.FestivalProtocolReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Bilet() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Bilet(Bilet other) : this() {
      spectacol_ = other.spectacol_ != null ? other.spectacol_.Clone() : null;
      cumparatorName_ = other.cumparatorName_;
      seats_ = other.seats_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Bilet Clone() {
      return new Bilet(this);
    }

    /// <summary>Field number for the "spectacol" field.</summary>
    public const int SpectacolFieldNumber = 1;
    private global::Ro.Mpp2025.Protobuffprotocol.Spectacol spectacol_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ro.Mpp2025.Protobuffprotocol.Spectacol Spectacol {
      get { return spectacol_; }
      set {
        spectacol_ = value;
      }
    }

    /// <summary>Field number for the "cumparatorName" field.</summary>
    public const int CumparatorNameFieldNumber = 2;
    private string cumparatorName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CumparatorName {
      get { return cumparatorName_; }
      set {
        cumparatorName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "seats" field.</summary>
    public const int SeatsFieldNumber = 3;
    private int seats_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Seats {
      get { return seats_; }
      set {
        seats_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Bilet);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Bilet other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Spectacol, other.Spectacol)) return false;
      if (CumparatorName != other.CumparatorName) return false;
      if (Seats != other.Seats) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (spectacol_ != null) hash ^= Spectacol.GetHashCode();
      if (CumparatorName.Length != 0) hash ^= CumparatorName.GetHashCode();
      if (Seats != 0) hash ^= Seats.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (spectacol_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Spectacol);
      }
      if (CumparatorName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(CumparatorName);
      }
      if (Seats != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Seats);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (spectacol_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Spectacol);
      }
      if (CumparatorName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(CumparatorName);
      }
      if (Seats != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Seats);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (spectacol_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Spectacol);
      }
      if (CumparatorName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CumparatorName);
      }
      if (Seats != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Seats);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Bilet other) {
      if (other == null) {
        return;
      }
      if (other.spectacol_ != null) {
        if (spectacol_ == null) {
          Spectacol = new global::Ro.Mpp2025.Protobuffprotocol.Spectacol();
        }
        Spectacol.MergeFrom(other.Spectacol);
      }
      if (other.CumparatorName.Length != 0) {
        CumparatorName = other.CumparatorName;
      }
      if (other.Seats != 0) {
        Seats = other.Seats;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (spectacol_ == null) {
              Spectacol = new global::Ro.Mpp2025.Protobuffprotocol.Spectacol();
            }
            input.ReadMessage(Spectacol);
            break;
          }
          case 18: {
            CumparatorName = input.ReadString();
            break;
          }
          case 24: {
            Seats = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (spectacol_ == null) {
              Spectacol = new global::Ro.Mpp2025.Protobuffprotocol.Spectacol();
            }
            input.ReadMessage(Spectacol);
            break;
          }
          case 18: {
            CumparatorName = input.ReadString();
            break;
          }
          case 24: {
            Seats = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Angajat : pb::IMessage<Angajat>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Angajat> _parser = new pb::MessageParser<Angajat>(() => new Angajat());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Angajat> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ro.Mpp2025.Protobuffprotocol.FestivalProtocolReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Angajat() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Angajat(Angajat other) : this() {
      username_ = other.username_;
      password_ = other.password_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Angajat Clone() {
      return new Angajat(this);
    }

    /// <summary>Field number for the "username" field.</summary>
    public const int UsernameFieldNumber = 1;
    private string username_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Username {
      get { return username_; }
      set {
        username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 2;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Angajat);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Angajat other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Username != other.Username) return false;
      if (Password != other.Password) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Username.Length != 0) hash ^= Username.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Username.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Username);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Username.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Username);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Username.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Angajat other) {
      if (other == null) {
        return;
      }
      if (other.Username.Length != 0) {
        Username = other.Username;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Username = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Username = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Request : pb::IMessage<Request>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Request> _parser = new pb::MessageParser<Request>(() => new Request());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ro.Mpp2025.Protobuffprotocol.FestivalProtocolReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request(Request other) : this() {
      type_ = other.type_;
      switch (other.PayloadCase) {
        case PayloadOneofCase.Angajat:
          Angajat = other.Angajat.Clone();
          break;
        case PayloadOneofCase.Day:
          Day = other.Day;
          break;
        case PayloadOneofCase.Bilet:
          Bilet = other.Bilet.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request Clone() {
      return new Request(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Ro.Mpp2025.Protobuffprotocol.Request.Types.Type type_ = global::Ro.Mpp2025.Protobuffprotocol.Request.Types.Type.Unkown;
    /// <summary>
    /// Identifies which request is filled in.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ro.Mpp2025.Protobuffprotocol.Request.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "angajat" field.</summary>
    public const int AngajatFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ro.Mpp2025.Protobuffprotocol.Angajat Angajat {
      get { return payloadCase_ == PayloadOneofCase.Angajat ? (global::Ro.Mpp2025.Protobuffprotocol.Angajat) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Angajat;
      }
    }

    /// <summary>Field number for the "day" field.</summary>
    public const int DayFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Day {
      get { return payloadCase_ == PayloadOneofCase.Day ? (string) payload_ : ""; }
      set {
        payload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        payloadCase_ = PayloadOneofCase.Day;
      }
    }

    /// <summary>Field number for the "bilet" field.</summary>
    public const int BiletFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ro.Mpp2025.Protobuffprotocol.Bilet Bilet {
      get { return payloadCase_ == PayloadOneofCase.Bilet ? (global::Ro.Mpp2025.Protobuffprotocol.Bilet) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Bilet;
      }
    }

    private object payload_;
    /// <summary>Enum of possible cases for the "payload" oneof.</summary>
    public enum PayloadOneofCase {
      None = 0,
      Angajat = 2,
      Day = 3,
      Bilet = 4,
    }
    private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadOneofCase PayloadCase {
      get { return payloadCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPayload() {
      payloadCase_ = PayloadOneofCase.None;
      payload_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!object.Equals(Angajat, other.Angajat)) return false;
      if (Day != other.Day) return false;
      if (!object.Equals(Bilet, other.Bilet)) return false;
      if (PayloadCase != other.PayloadCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Ro.Mpp2025.Protobuffprotocol.Request.Types.Type.Unkown) hash ^= Type.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Angajat) hash ^= Angajat.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Day) hash ^= Day.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Bilet) hash ^= Bilet.GetHashCode();
      hash ^= (int) payloadCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Ro.Mpp2025.Protobuffprotocol.Request.Types.Type.Unkown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.Angajat) {
        output.WriteRawTag(18);
        output.WriteMessage(Angajat);
      }
      if (payloadCase_ == PayloadOneofCase.Day) {
        output.WriteRawTag(26);
        output.WriteString(Day);
      }
      if (payloadCase_ == PayloadOneofCase.Bilet) {
        output.WriteRawTag(34);
        output.WriteMessage(Bilet);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Ro.Mpp2025.Protobuffprotocol.Request.Types.Type.Unkown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.Angajat) {
        output.WriteRawTag(18);
        output.WriteMessage(Angajat);
      }
      if (payloadCase_ == PayloadOneofCase.Day) {
        output.WriteRawTag(26);
        output.WriteString(Day);
      }
      if (payloadCase_ == PayloadOneofCase.Bilet) {
        output.WriteRawTag(34);
        output.WriteMessage(Bilet);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Ro.Mpp2025.Protobuffprotocol.Request.Types.Type.Unkown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.Angajat) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Angajat);
      }
      if (payloadCase_ == PayloadOneofCase.Day) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Day);
      }
      if (payloadCase_ == PayloadOneofCase.Bilet) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Bilet);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Request other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Ro.Mpp2025.Protobuffprotocol.Request.Types.Type.Unkown) {
        Type = other.Type;
      }
      switch (other.PayloadCase) {
        case PayloadOneofCase.Angajat:
          if (Angajat == null) {
            Angajat = new global::Ro.Mpp2025.Protobuffprotocol.Angajat();
          }
          Angajat.MergeFrom(other.Angajat);
          break;
        case PayloadOneofCase.Day:
          Day = other.Day;
          break;
        case PayloadOneofCase.Bilet:
          if (Bilet == null) {
            Bilet = new global::Ro.Mpp2025.Protobuffprotocol.Bilet();
          }
          Bilet.MergeFrom(other.Bilet);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Ro.Mpp2025.Protobuffprotocol.Request.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            global::Ro.Mpp2025.Protobuffprotocol.Angajat subBuilder = new global::Ro.Mpp2025.Protobuffprotocol.Angajat();
            if (payloadCase_ == PayloadOneofCase.Angajat) {
              subBuilder.MergeFrom(Angajat);
            }
            input.ReadMessage(subBuilder);
            Angajat = subBuilder;
            break;
          }
          case 26: {
            Day = input.ReadString();
            break;
          }
          case 34: {
            global::Ro.Mpp2025.Protobuffprotocol.Bilet subBuilder = new global::Ro.Mpp2025.Protobuffprotocol.Bilet();
            if (payloadCase_ == PayloadOneofCase.Bilet) {
              subBuilder.MergeFrom(Bilet);
            }
            input.ReadMessage(subBuilder);
            Bilet = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Ro.Mpp2025.Protobuffprotocol.Request.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            global::Ro.Mpp2025.Protobuffprotocol.Angajat subBuilder = new global::Ro.Mpp2025.Protobuffprotocol.Angajat();
            if (payloadCase_ == PayloadOneofCase.Angajat) {
              subBuilder.MergeFrom(Angajat);
            }
            input.ReadMessage(subBuilder);
            Angajat = subBuilder;
            break;
          }
          case 26: {
            Day = input.ReadString();
            break;
          }
          case 34: {
            global::Ro.Mpp2025.Protobuffprotocol.Bilet subBuilder = new global::Ro.Mpp2025.Protobuffprotocol.Bilet();
            if (payloadCase_ == PayloadOneofCase.Bilet) {
              subBuilder.MergeFrom(Bilet);
            }
            input.ReadMessage(subBuilder);
            Bilet = subBuilder;
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Request message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("Unkown")] Unkown = 0,
        [pbr::OriginalName("Login")] Login = 1,
        [pbr::OriginalName("GetSpectacole")] GetSpectacole = 2,
        [pbr::OriginalName("FilterSpectacole")] FilterSpectacole = 3,
        [pbr::OriginalName("ReserveBilet")] ReserveBilet = 4,
      }

    }
    #endregion

  }

  public sealed partial class Response : pb::IMessage<Response>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Response> _parser = new pb::MessageParser<Response>(() => new Response());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ro.Mpp2025.Protobuffprotocol.FestivalProtocolReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response(Response other) : this() {
      type_ = other.type_;
      error_ = other.error_;
      spectacole_ = other.spectacole_.Clone();
      filtered_ = other.filtered_.Clone();
      angajat_ = other.angajat_ != null ? other.angajat_.Clone() : null;
      spectacol_ = other.spectacol_ != null ? other.spectacol_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response Clone() {
      return new Response(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Ro.Mpp2025.Protobuffprotocol.Response.Types.Type type_ = global::Ro.Mpp2025.Protobuffprotocol.Response.Types.Type.Unknown;
    /// <summary>
    /// Identifies which request is filled in.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ro.Mpp2025.Protobuffprotocol.Response.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 2;
    private string error_ = "";
    /// <summary>
    /// One of the following will be filled in, depending on the type.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Error {
      get { return error_; }
      set {
        error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "spectacole" field.</summary>
    public const int SpectacoleFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Ro.Mpp2025.Protobuffprotocol.Spectacol> _repeated_spectacole_codec
        = pb::FieldCodec.ForMessage(26, global::Ro.Mpp2025.Protobuffprotocol.Spectacol.Parser);
    private readonly pbc::RepeatedField<global::Ro.Mpp2025.Protobuffprotocol.Spectacol> spectacole_ = new pbc::RepeatedField<global::Ro.Mpp2025.Protobuffprotocol.Spectacol>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Ro.Mpp2025.Protobuffprotocol.Spectacol> Spectacole {
      get { return spectacole_; }
    }

    /// <summary>Field number for the "filtered" field.</summary>
    public const int FilteredFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Ro.Mpp2025.Protobuffprotocol.Spectacol> _repeated_filtered_codec
        = pb::FieldCodec.ForMessage(34, global::Ro.Mpp2025.Protobuffprotocol.Spectacol.Parser);
    private readonly pbc::RepeatedField<global::Ro.Mpp2025.Protobuffprotocol.Spectacol> filtered_ = new pbc::RepeatedField<global::Ro.Mpp2025.Protobuffprotocol.Spectacol>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Ro.Mpp2025.Protobuffprotocol.Spectacol> Filtered {
      get { return filtered_; }
    }

    /// <summary>Field number for the "angajat" field.</summary>
    public const int AngajatFieldNumber = 5;
    private global::Ro.Mpp2025.Protobuffprotocol.Angajat angajat_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ro.Mpp2025.Protobuffprotocol.Angajat Angajat {
      get { return angajat_; }
      set {
        angajat_ = value;
      }
    }

    /// <summary>Field number for the "spectacol" field.</summary>
    public const int SpectacolFieldNumber = 6;
    private global::Ro.Mpp2025.Protobuffprotocol.Spectacol spectacol_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ro.Mpp2025.Protobuffprotocol.Spectacol Spectacol {
      get { return spectacol_; }
      set {
        spectacol_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (Error != other.Error) return false;
      if(!spectacole_.Equals(other.spectacole_)) return false;
      if(!filtered_.Equals(other.filtered_)) return false;
      if (!object.Equals(Angajat, other.Angajat)) return false;
      if (!object.Equals(Spectacol, other.Spectacol)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Ro.Mpp2025.Protobuffprotocol.Response.Types.Type.Unknown) hash ^= Type.GetHashCode();
      if (Error.Length != 0) hash ^= Error.GetHashCode();
      hash ^= spectacole_.GetHashCode();
      hash ^= filtered_.GetHashCode();
      if (angajat_ != null) hash ^= Angajat.GetHashCode();
      if (spectacol_ != null) hash ^= Spectacol.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Ro.Mpp2025.Protobuffprotocol.Response.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Error);
      }
      spectacole_.WriteTo(output, _repeated_spectacole_codec);
      filtered_.WriteTo(output, _repeated_filtered_codec);
      if (angajat_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Angajat);
      }
      if (spectacol_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Spectacol);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Ro.Mpp2025.Protobuffprotocol.Response.Types.Type.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Error);
      }
      spectacole_.WriteTo(ref output, _repeated_spectacole_codec);
      filtered_.WriteTo(ref output, _repeated_filtered_codec);
      if (angajat_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Angajat);
      }
      if (spectacol_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Spectacol);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Ro.Mpp2025.Protobuffprotocol.Response.Types.Type.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Error.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
      }
      size += spectacole_.CalculateSize(_repeated_spectacole_codec);
      size += filtered_.CalculateSize(_repeated_filtered_codec);
      if (angajat_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Angajat);
      }
      if (spectacol_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Spectacol);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Response other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Ro.Mpp2025.Protobuffprotocol.Response.Types.Type.Unknown) {
        Type = other.Type;
      }
      if (other.Error.Length != 0) {
        Error = other.Error;
      }
      spectacole_.Add(other.spectacole_);
      filtered_.Add(other.filtered_);
      if (other.angajat_ != null) {
        if (angajat_ == null) {
          Angajat = new global::Ro.Mpp2025.Protobuffprotocol.Angajat();
        }
        Angajat.MergeFrom(other.Angajat);
      }
      if (other.spectacol_ != null) {
        if (spectacol_ == null) {
          Spectacol = new global::Ro.Mpp2025.Protobuffprotocol.Spectacol();
        }
        Spectacol.MergeFrom(other.Spectacol);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Ro.Mpp2025.Protobuffprotocol.Response.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            Error = input.ReadString();
            break;
          }
          case 26: {
            spectacole_.AddEntriesFrom(input, _repeated_spectacole_codec);
            break;
          }
          case 34: {
            filtered_.AddEntriesFrom(input, _repeated_filtered_codec);
            break;
          }
          case 42: {
            if (angajat_ == null) {
              Angajat = new global::Ro.Mpp2025.Protobuffprotocol.Angajat();
            }
            input.ReadMessage(Angajat);
            break;
          }
          case 50: {
            if (spectacol_ == null) {
              Spectacol = new global::Ro.Mpp2025.Protobuffprotocol.Spectacol();
            }
            input.ReadMessage(Spectacol);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Ro.Mpp2025.Protobuffprotocol.Response.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            Error = input.ReadString();
            break;
          }
          case 26: {
            spectacole_.AddEntriesFrom(ref input, _repeated_spectacole_codec);
            break;
          }
          case 34: {
            filtered_.AddEntriesFrom(ref input, _repeated_filtered_codec);
            break;
          }
          case 42: {
            if (angajat_ == null) {
              Angajat = new global::Ro.Mpp2025.Protobuffprotocol.Angajat();
            }
            input.ReadMessage(Angajat);
            break;
          }
          case 50: {
            if (spectacol_ == null) {
              Spectacol = new global::Ro.Mpp2025.Protobuffprotocol.Spectacol();
            }
            input.ReadMessage(Spectacol);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Response message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("Unknown")] Unknown = 0,
        [pbr::OriginalName("Ok")] Ok = 1,
        [pbr::OriginalName("Error")] Error = 2,
        [pbr::OriginalName("GetSpectacole")] GetSpectacole = 3,
        [pbr::OriginalName("FilterSpectacole")] FilterSpectacole = 4,
        [pbr::OriginalName("ReserveBilet")] ReserveBilet = 5,
        [pbr::OriginalName("Spectacole")] Spectacole = 6,
        [pbr::OriginalName("updateSpectacol")] UpdateSpectacol = 7,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
